name: Docker Base Auto Update CI

on:
  schedule:
    - cron: "23 13 3 * *"

jobs:
  check:
    name: Base update check
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - 
	name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: alpine:latest
          image: simeononsecurity/docker-vlmcsd:latest
  build:
    name: Build and publish
    needs: [check]
    if: needs.check.outputs.needs-updating == 'true'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            simeononsecurity/docker-vlmcsd
          flavor: |
            latest=true
          tags: |
            type=schedule,pattern=latest
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: simeononsecurity
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6, linux/386, linux/ppc64le, linux/s390x
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=simeononsecurity/docker-vlmcsd:buildcache
          cache-to: |
            type=registry,ref=simeononsecurity/docker-vlmcsd:buildcache,mode=max
